name = "bp-prod"
account_id = "58a108d999123422a8ecab8beaffbac9"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2022-11-27"
workers_dev = true

kv_namespaces = [
  { binding = "BP_DB", preview_id = "e629ff8337aa4de0964126648496d220", id = "e629ff8337aa4de0964126648496d220" }
]
